services:
  angular:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "4200:4200"
    command: "/bin/sh -c 'while :; do sleep 10; done'"